### ISSUE TITLE
SELinux permissive should be more prominent

### ISSUE THREAD

**Issue by LoganDark** [FerryAr/lhroot#1]
In your README.md, the fact that this module changes SELinux to permissive is a small footnote at the bottom. I think it should be more prominent, because MagiskHide can not always hide permissive SELinux (it can still break safetynet)

**Comment by FerryAr** [comment]
maybe I'll make the setting of SELinux to be optional.

**Comment by LoganDark** [comment]
If you now don't do it yourself, you should still make sure to let people know that setting SELinux to permissive may be required to make Linux behave properly.

**Comment by FerryAr** [comment]
The chroot is working properly with Enforcing SELinux, As far as I know now, no alsa support if SELinux is Enforcing.
