### ISSUE TITLE
My phone bricked after running this.

### ISSUE THREAD

**Issue by Kuba112811** [FerryAr/lhroot#10]
After i uninstalled the chroot i didn t reboot in the 30 seconds, and now my phone boots and says 'Phone is starting' and it s stuck there. Any help in unbricking?
My device: Redmi note 9
System: Octavi Os (Android 11)

**Comment by vvvintage** [comment]
You can't uninstall the chroot before you unmount and reboot.

**Comment by FerryAr** [comment]
Are you directly use rm -rf or use lhroot?
In lhroot script, I am definitely give time to reboot if dev isn't successfully unmounted.

**Comment by lexavey** [comment]
hey , all my data IS GONE
THANKS
