### ISSUE TITLE
BEWARE YOUR PHONE BRICKED

### ISSUE THREAD

**Issue by lexavey** [FerryAr/lhroot#12]
Device : crDroidAndroid-12.1-20220816-spes-v8.9
THANKS MAN
ALL MY BACKUP IS GONE DATA GONE PHOTO GONE DOCUMENT
NOW START AGAIN FROM STRATCH

VERRY THANKS BECAUSE THIS MODULE 
I CANT SAY ANYTHING AGAIN
I JUST USE MENU REMOVE CHROOT 
I THINK JUST ONLY REMOVE THE CHROOT
BUT THE MENU OF REMOVE CHROOT LIKE A RM -RF /
I WANT CRYING NOW BUT I CANT
ITS MY FAULT OR NOT IDK

i try to read sdcard data with adb, totally GONE

EDIT : IAM SO PANIC

MTP is broken, then i reboot to twrp, finally works, i backup all my /data and /sdcard
backup /data with TWRP
then backup all data to PC using adb
adb pull /sdcard/. backup

and flash the phone again...

**Comment by HilmiRidho** [comment]
Aww maaann  😰

**Comment by FerryAr** [comment]
> Device : crDroidAndroid-12.1-20220816-spes-v8.9
> THANKS MAN
> ALL MY BACKUP IS GONE DATA GONE PHOTO GONE DOCUMENT
> NOW START AGAIN FROM STRATCH
> 
> 
> VERRY THANKS BECAUSE THIS MODULE 
> I CANT SAY ANYTHING AGAIN
> I JUST USE MENU REMOVE CHROOT 
> I THINK JUST ONLY REMOVE THE CHROOT
> BUT THE MENU OF REMOVE CHROOT LIKE A RM -RF /
> I WANT CRYING NOW BUT I CANT
> ITS MY FAULT OR NOT IDK
> 
> 
> i try to read sdcard data with adb, totally GONE
> 
> EDIT : IAM SO PANIC
> 
> MTP is broken, then i reboot to twrp, finally works, i backup all my /data and /sdcard
> backup /data with TWRP
> then backup all data to PC using adb
> adb pull /sdcard/. backup
> 
> and flash the phone again...
> 

Its unfortunate, but are you understand at all about Linux environment? Just unmount or for easier solution just reboot prior to deleting.
