### ISSUE TITLE
Cannot resolve any apt repositories to update

### ISSUE THREAD

**Issue by tooandrew** [FerryAr/lhroot#13]
I've tried adding ones i found online to sources.list
Ive tried adding a resolv.conf with known good dns to /etc
It fails to resolve any apt repositories to update, including the included one. 
Ping wasnt included but I was able to wget a zip from github, so the network is live.
I managed to install net-tools, openresolv and iputils-ping from packages. Ping also cant resolve any names.

Lhroot shows busybox as being unavailable but installed successfully but without a package manager it is not much good to me because i am a noob. I just want to mount a shared windows folder and run a script to update an avahi-daemon service when a port number changes on a file in the windows folder.

**Comment by FerryAr** [comment]
have you tried solution on #8 ?
