### ISSUE TITLE
Boot into Linux Chroot when device startup

### ISSUE THREAD

**Issue by titanhw** [FerryAr/lhroot#14]
Do you have any plan to support boot into Linux Chroot when device startup?
Currently I edit a shell script and put it into /data/adb/service.d to auto run bootlinux command.
Are there any better solutions?

Thanks.

**Comment by FerryAr** [comment]
Since it's user preference, I don't have any plan to implement that soon.

**Comment by puneetred** [comment]
@TitanWhoo is it possible for you to share the script?

**Comment by TitanWhoo** [comment]
> @TitanWhoo is it possible for you to share the script?

Assuming you have installed the "lhroot" Magisk module
You can easily place the following script in the Magisk's boot script directory (/data/adb/service.d):
```
#!/bin/sh
/system/bin/bootlinux
```

Assuming the script is named "lhroot.sh," grant it executable permissions using the command: 

`chmod +x /data/adb/service.d/lhroot.sh`

Restart your device, and you will see that the Linux system will automatically start alongside the device during boot-up.

This is a feature of Magisk, you can refer to the following link for more information: [Magisk Guides - Boot Scripts](https://topjohnwu.github.io/Magisk/guides.html#boot-scripts)
