### ISSUE TITLE
manjaro and debian i3wm cannot open display on termux-x11

### ISSUE THREAD

**Issue by Chuanhuan** [FerryAr/lhroot#17]
Have anyone succeeded to run any desktop enviroment or windows manager on termux-X11?

Update: 
The XSDL is working on both distro. Just curious I follow all steps why termux-X11 failed to open display.

**Comment by FerryAr** [comment]
> Have anyone succeeded to run any desktop enviroment or windows manager on termux-X11?
> 
> Update: The XSDL is working on both distro. Just curious I follow all steps why termux-X11 failed to open display.

I've never tested it, I am usually use Xvfb + x11vnc then access it using RealVNC for x11.

**Comment by Chuanhuan** [comment]
Ok, I think I figured out.
In termux, 

```
export XDG_RUNTIME_DIR=${TMPDIR}
export CHROOT_DIR=/data/manjaro
sudo busybox mount --bind $PREFIX/tmp $CHROOT_DIR/tmp
```
Run `termux-x11 -ac`

------
In chroot, 
```
echo DISPLAY=:0
i3
```
