### ISSUE TITLE
Removing the chroot removed data of all installed apps

### ISSUE THREAD

**Issue by ay0ks** [FerryAr/lhroot#18]
I've tried to remove chroot using the menu item, after restart I've discovered that data of all installed apps was removed (google authenticator codes, logins in discord, etc.)

**Comment by FerryAr** [comment]
> I've tried to remove chroot using the menu item, after restart I've discovered that data of all installed apps was removed (google authenticator codes, logins in discord, etc.)

please make sure, all mountpoint on chroot is unmounted before unintsalling
