### ISSUE TITLE
help ! 

### ISSUE THREAD

**Issue by YuaVN** [FerryAr/lhroot#19]
on7xelte:/data/data/com.termux/files/home #bootlinux
Mounting Linux Chroot...
/system/bin/bootlinux: /system/bin/bootlinux_init[252]: can't create /data/ubuntu/etc/resolv.conf: No such file or directory
/system/bin/bootlinux: /system/bin/bootlinux_init[252]: can't create /data/ubuntu/etc/resolv.conf: No such file or directory
/system/bin/bootlinux: /system/bin/bootlinux_init[252]: can't create /data/ubuntu/etc/resolv.conf: No such file or directory
/system/bin/bootlinux: /system/bin/bootlinux_init[252]: can't create /data/ubuntu/etc/resolv.conf: No such file or directory
/system/bin/bootlinux: /system/bin/bootlinux_init[252]: can't create /data/ubuntu/etc/resolv.conf: No such file or directory
chmod: /data/ubuntu/etc/resolv.conf: No such file or directory
mount: mounting /system/lib/modules on /data/ubuntu/lib/modules failed: No such file or directory
sysctl: error: 'kernel.shmmax' is an unknown key
/system/bin/bootlinux: /system/bin/bootlinux_init[252]: can't create /data/ubuntu/etc/resolv.conf: No such file or directory
/system/bin/bootlinux: /system/bin/bootlinux_init[252]: can't create /data/ubuntu/etc/resolv.conf: No such file or directory
/system/bin/bootlinux: /system/bin/bootlinux_init[252]: can't create /data/ubuntu/etc/resolv.conf: No such file or directory
sysctl: error: 'kernel.shmmax' is an unknown key
net.ipv4.ip_forward = 1
/system/bin/bootlinux: /system/bin/bootlinux_init[252]: can't create /data/ubuntu/etc/hosts: No such file or directory
/system/bin/bootlinux: /system/bin/bootlinux_init[252]: can't create /data/ubuntu/etc/hosts: No such file or directory
The Linux chroot has been started.
Missing required folder, exit now....

**Comment by FerryAr** [comment]
> on7xelte:/data/data/com.termux/files/home #bootlinux Mounting Linux Chroot... /system/bin/bootlinux: /system/bin/bootlinux_init[252]: can't create /data/ubuntu/etc/resolv.conf: No such file or directory /system/bin/bootlinux: /system/bin/bootlinux_init[252]: can't create /data/ubuntu/etc/resolv.conf: No such file or directory /system/bin/bootlinux: /system/bin/bootlinux_init[252]: can't create /data/ubuntu/etc/resolv.conf: No such file or directory /system/bin/bootlinux: /system/bin/bootlinux_init[252]: can't create /data/ubuntu/etc/resolv.conf: No such file or directory /system/bin/bootlinux: /system/bin/bootlinux_init[252]: can't create /data/ubuntu/etc/resolv.conf: No such file or directory chmod: /data/ubuntu/etc/resolv.conf: No such file or directory mount: mounting /system/lib/modules on /data/ubuntu/lib/modules failed: No such file or directory sysctl: error: 'kernel.shmmax' is an unknown key /system/bin/bootlinux: /system/bin/bootlinux_init[252]: can't create /data/ubuntu/etc/resolv.conf: No such file or directory /system/bin/bootlinux: /system/bin/bootlinux_init[252]: can't create /data/ubuntu/etc/resolv.conf: No such file or directory /system/bin/bootlinux: /system/bin/bootlinux_init[252]: can't create /data/ubuntu/etc/resolv.conf: No such file or directory sysctl: error: 'kernel.shmmax' is an unknown key net.ipv4.ip_forward = 1 /system/bin/bootlinux: /system/bin/bootlinux_init[252]: can't create /data/ubuntu/etc/hosts: No such file or directory /system/bin/bootlinux: /system/bin/bootlinux_init[252]: can't create /data/ubuntu/etc/hosts: No such file or directory The Linux chroot has been started. Missing required folder, exit now....

are you following the instruction carefully?
