### ISSUE TITLE
Access termux

### ISSUE THREAD

**Issue by stein-dev** [FerryAr/lhroot#2]
Can i request a feature to allow accessing termux-api with this? This might help you if plan to implement this. https://github.com/termux/termux-api/issues/369

**Comment by FerryAr** [comment]
support added, use it with selinux permissive

**Comment by abursmh** [comment]
> Can i request a feature to allow accessing termux-api with this? This might help you if plan to implement this. https://github.com/termux/termux-api/issues/369
