### ISSUE TITLE
Black screen after remove chroot

### ISSUE THREAD

**Issue by binhvo7794** [FerryAr/lhroot#21]
When i remove Ubuntu chroot (using lhroot command), my phone black screen, need to power off use vol up + power and restart again, it look like bricked, you make me so scariest!

**Comment by FerryAr** [comment]
if you uninstall via lhroot, you must have seen this message 
https://github.com/FerryAr/lhroot/blob/5c916bc3c5a1c9ff359a3c61348c4657b3510733/system/bin/lhroot#L429-L440

If the killlinux command is logging something like this:
> umount: can't unmount /dev resource busy

I am telling you to reboot your phone to ensure that all mountpoint is already unmounted. I already give you 15 seconds!

**Comment by ktg-72** [comment]
Holy grammar
