### ISSUE TITLE
Can't remove kali chroot

### ISSUE THREAD

**Issue by binhvo7794** [FerryAr/lhroot#25]
When i remove chroot from lhroot, it show this error, when i restart the /data/kali is still there, can't not remove 
![Screenshot_2023-02-24-11-20-41-25_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/66165345/221091286-80828d63-006d-4c07-a0a7-c7222bd7edee.jpg)

**Comment by FerryAr** [comment]
Reboot and try to remove again
