### ISSUE TITLE
Error module not dectected

### ISSUE THREAD

**Issue by TimeFused** [FerryAr/lhroot#26]
Hlo I use spark os 13.4 android custom ROM with android 13 when I try to install lhroot in termux its show error module not decteced
![Screenshot_20230228-144828_Termux](https://user-images.githubusercontent.com/112058926/221808073-dd3304ae-ca84-4fbc-847c-03b2ef85d1a1.png)

**Comment by TimeFused** [comment]
And last time when I install its Ubuntu os show error when I use curl github.com error like ( git curl: (6) could not resolve host: git)

**Comment by FerryAr** [comment]
> Hlo I use spark os 13.4 android custom ROM with android 13 when I try to install lhroot in termux its show error module not decteced ![Screenshot_20230228-144828_Termux](https://user-images.githubusercontent.com/112058926/221808073-dd3304ae-ca84-4fbc-847c-03b2ef85d1a1.png)

Show me the output of

`ls /data/adb/modules/lhroot`

And
`which lhroot`

**Comment by TimeFused** [comment]
Hlo bro error module not decteced this error fix but ( git curl: (6) could not resolve host: git) this error also show when use curl git and ping github.com not work on normal user

**Comment by Chuanhuan** [comment]
How did you solve this issue?
My lhroot
```
Android# which lhroot
/system/bin/lhroot
Android# ls /data/adb/modules/lhroot
mod-util.sh  module.prop  system
```
looks ok to me.

for you network, try this:
```
echo "nameserver 8.8.8.8" >> /etc/resolv.conf

addgroup --gid 3003 android_inet

usermod -g android_inet _apt

```
