### ISSUE TITLE
custom mount point

### ISSUE THREAD

**Issue by jwchen119** [FerryAr/lhroot#28]
Hi,

I'm trying to use this method to install klipper.
But now I need to add a new mount point at  "/data/data/com.octo4a/files" to use the serial from another app in chroot.
How to achieve that?

**Comment by FerryAr** [comment]
just mount using busybox from android terminal

e.g
`busybox mount /data/data/com.octo4a/files /data/debian/mnt`

**Comment by jwchen119** [comment]
Thanks!
That's clever.
