### ISSUE TITLE
 Module not detected

### ISSUE THREAD

**Issue by Chuanhuan** [FerryAr/lhroot#34]
I root my android 13 tablet with magisk delta and got an error message.
There is no problem with creating chroot container by using third party script. However, I just can't use lhroot.
 Can someone help me?

```
:/data/data/com.termux/files/home/Ubuntu-chroot-scripts # lhroot
Module not detected!
1|:/data/data/com.termux/files/home/Ubuntu-chroot-scripts # which lhroot
/system/bin/lhroot
```

**Comment by arunas-smala** [comment]
same here..

**Comment by Chuanhuan** [comment]
Ok, I thought I was the only one who had this issue.

I did find a temporary solution after I looked at the raw code. Just download roofs and extract in `/data/roofname`. Then `bootlinux` to the folder. I'm not sure this is safe or not but it works really well on my manjaro.

**Comment by arunas-smala** [comment]
I also found a solution looking at source code. I changed `/sbin/.magisk` to `/debug_ramdisk/.magisk` in `lhroot.sh` file, first unzipped, changed this line, zipped again and uploaded to Magisk
