### ISSUE TITLE
Arch Linux ARM: pacman -Su fails with "could not determine cachedir mount point /var/cache/pacman/pkg"

### ISSUE THREAD

**Issue by RealEthanPlayzDev** [FerryAr/lhroot#36]
```
error: could not determine cachedir mount point /var/cache/pacman/pkg
error: failed to commit transaction (not enough free disk space)
Errors occurred, no packages were upgraded.
```

Android 13
Magisk v26.3 (Zygisk enabled)
Termux as terminal emulator (su)
And before you ask, yes I do have free disk space (there's at least 50 GB of free space)

``/var/cache/pacman/pkg`` does exist as a directory

**Comment by FerryAr** [comment]
> could not determine cachedir mount point /var/cache/pacman/pkg

Comment ```CheckSpace``` on /etc/pacman.conf

**Comment by RealEthanPlayzDev** [comment]
@FerryAr That fixed it, thanks!
