### ISSUE TITLE
Module not detected

### ISSUE THREAD

**Issue by RchrdAriza** [FerryAr/lhroot#43]
![Screenshot_20231223-142914_Termux](https://github.com/FerryAr/lhroot/assets/128317303/31838e87-e316-452d-abdb-d4c5188b6dad)
Phone: Samsung Galaxy A21s
Android 12

**Comment by ghost** [comment]
~I got same error on Samsung A30s, Android 11~

**Comment by Fdydhchxy54645** [comment]
I got same error on Poco m2 Android 11

**Comment by ghost** [comment]
I managed to solve it following the tip of a user in #34 
First I unzipped the module, changed /sbin/.magisk to /debug_ramdisk/.magisk in lhroot.sh file, zipped it again and uploaded it to Magisk.

Edit: For some reason, this solution stopped working on my Samsung A30s, Android 11. Idk why. 🤷🏻

**Comment by RchrdAriza** [comment]
> I managed to solve it following the tip of a user in #34 First I unzipped the module, changed /sbin/.magisk to /debug_ramdisk/.magisk in lhroot.sh file, zipped it again and uploaded it to Magisk.

Did you change both? Or just the first match? By the way, I found this file in system/bin/lhroot.sh after extracting the zip
![Screenshot_20231227-015247_Termux](https://github.com/FerryAr/lhroot/assets/128317303/898657d6-7f39-4603-80d8-7cf3211ea5a7)

**Comment by ghost** [comment]
I changed both

**Comment by RchrdAriza** [comment]
> I changed both

Thanks, I'll try

**Comment by RchrdAriza** [comment]
Thank you very much, it worked 🙌🏻

![Screenshot_20231227-022409_Termux](https://github.com/FerryAr/lhroot/assets/128317303/1e397f70-608e-480a-ae03-b904d871d8a4)

**Comment by ghoste0001** [comment]
i changed it to:

``# Magisk Mod Directory
[ -d "/data/adb/" ] && MOUNTPATH="/data/adb/modules" || MOUNTPATH="$(find /dev -mindepth 2 -maxdepth 2 -type d -name ".magisk")/modules"
MODDIR="$MOUNTPATH/$ID"``

and it works perfectly (Magisk 27.0, lhroot 2.2.0)
