### ISSUE TITLE
I don't know if chroot is booting

### ISSUE THREAD

**Issue by Mateus13000** [FerryAr/lhroot#6]
That's what happens when I use bootlinux

Mounting Linux Chroot...
/system/bin/bootlinux: /system/bin/bootlinux_init[293]: cd: /apex: No such file or directory
/system/bin/bootlinux: /system/bin/bootlinux_init[293]: cd: no OLDPWD
[+] mounted /dev/pts
[+] mounted /proc
[+] mounted /sys
/system/bin/bootlinux: /system/bin/bootlinux_init[293]: cd: /apex: No such file or directory
mount: mounting /apex/acct on /data/arch/apex/acct failed: No such file or directory
mount: mounting /apex/bin on /data/arch/apex/bin failed: No such file or directory
mount: mounting /apex/bugreports on /data/arch/apex/bugreports failed: No such file or directory
mount: mounting /apex/cache on /data/arch/apex/cache failed: No such file or directory
mount: mounting /apex/charger on /data/arch/apex/charger failed: No such file or directory
mount: mounting /apex/config on /data/arch/apex/config failed: No such file or directory
mount: mounting /apex/d on /data/arch/apex/d failed: No such file or directory
mount: mounting /apex/data on /data/arch/apex/data failed: No such file or directory
mount: mounting /apex/default.prop on /data/arch/apex/default.prop failed: No such file or directory
mount: mounting /apex/dev on /data/arch/apex/dev failed: No such file or directory
mount: mounting /apex/efs on /data/arch/apex/efs failed: No such file or directory
mount: mounting /apex/etc on /data/arch/apex/etc failed: No such file or directory
mount: mounting /apex/file_contexts.bin on /data/arch/apex/file_contexts.bin failed: No such file or directory
mount: mounting /apex/fstab.sc8830 on /data/arch/apex/fstab.sc8830 failed: No such file or directory
mount: mounting /apex/init on /data/arch/apex/init failed: No such file or directory
mount: mounting /apex/init.board.rc on /data/arch/apex/init.board.rc failed: No such file or directory
mount: mounting /apex/init.cm.rc on /data/arch/apex/init.cm.rc failed: No such file or directory
mount: mounting /apex/init.environ.rc on /data/arch/apex/init.environ.rc failed: No such file or directory
mount: mounting /apex/init.gtel3g_base.rc on /data/arch/apex/init.gtel3g_base.rc failed: No such file or directory
mount: mounting /apex/init.rc on /data/arch/apex/init.rc failed: No such file or directory
mount: mounting /apex/init.sc8830.rc on /data/arch/apex/init.sc8830.rc failed: No such file or directory
mount: mounting /apex/init.sc8830.usb.rc on /data/arch/apex/init.sc8830.usb.rc failed: No such file or directory
mount: mounting /apex/init.usb.configfs.rc on /data/arch/apex/init.usb.configfs.rc failed: No such file or directory
mount: mounting /apex/init.usb.rc on /data/arch/apex/init.usb.rc failed: No such file or directory
mount: mounting /apex/init.wifi.rc on /data/arch/apex/init.wifi.rc failed: No such file or directory
mount: mounting /apex/init.zygote32.rc on /data/arch/apex/init.zygote32.rc failed: No such file or directory
mount: mounting /apex/mnt on /data/arch/apex/mnt failed: No such file or directory
mount: mounting /apex/oem on /data/arch/apex/oem failed: No such file or directory
mount: mounting /apex/preload on /data/arch/apex/preload failed: No such file or directory
mount: mounting /apex/proc on /data/arch/apex/proc failed: No such file or directory
mount: mounting /apex/productinfo on /data/arch/apex/productinfo failed: No such file or directory
mount: mounting /apex/property_contexts on /data/arch/apex/property_contexts failed: No such file or directory
mount: mounting /apex/res on /data/arch/apex/res failed: No such file or directory
mount: mounting /apex/root on /data/arch/apex/root failed: No such file or directory
mount: mounting /apex/sbin on /data/arch/apex/sbin failed: No such file or directory
mount: mounting /apex/sdcard on /data/arch/apex/sdcard failed: No such file or directory
mount: mounting /apex/seapp_contexts on /data/arch/apex/seapp_contexts failed: No such file or directory
mount: mounting /apex/selinux_version on /data/arch/apex/selinux_version failed: No such file or directory
mount: mounting /apex/sepolicy on /data/arch/apex/sepolicy failed: No such file or directory
mount: mounting /apex/service_contexts on /data/arch/apex/service_contexts failed: No such file or directory
mount: mounting /apex/storage on /data/arch/apex/storage failed: No such file or directory
mount: mounting /apex/sys on /data/arch/apex/sys failed: No such file or directory
mount: mounting /apex/system on /data/arch/apex/system failed: No such file or directory
mount: mounting /apex/ueventd.rc on /data/arch/apex/ueventd.rc failed: No such file or directory
mount: mounting /apex/ueventd.sc8830.rc on /data/arch/apex/ueventd.sc8830.rc failed: No such file or directory
mount: mounting /apex/vendor on /data/arch/apex/vendor failed: No such file or directory
[+] mounted /data/data
[+] mounted /data/dalvik-cache
mount: mounting /linkerconfig on /data/arch/linkerconfig failed: No such file or directory
[+] mounted /system
net.ipv4.ip_forward = 1
The Linux chroot has been started.
The Linux chroot should be already running!

chroot: can't execute '/usr/bin/env': No such file or directory

**Comment by FerryAr** [comment]
What android version?

**Comment by Mateus13000** [comment]
Android 7.1.2 
arm32 
Magisk 24.3, I'm using just the lhroot and busybox mudules.

**Comment by FerryAr** [comment]
> Android 7.1.2 arm32 Magisk 24.3, I'm using just the lhroot and busybox mudules.

Apex folder was introduced in Android 10
https://source.android.com/devices/tech/ota/apex

Have you tried other distro? Arch Linux ARM is untested apparently because the tarball size is so big

**Comment by Mateus13000** [comment]
I tried Ubuntu, but didn't work...
