### ISSUE TITLE
Ubuntu is not updating.

### ISSUE THREAD

**Issue by Mateus13000** [FerryAr/lhroot#8]
![IMG_20220702_170046](https://user-images.githubusercontent.com/38146322/177014751-84e5be17-70a1-4fcb-addc-a0fb2cae3844.jpg)

**Comment by FerryAr** [comment]
Can you access http://ports.ubuntu.com via browser? Is ping command work?

**Comment by FerryAr** [comment]
![Screenshot_20220704-150343_Termux](https://user-images.githubusercontent.com/38641932/177110178-28eda951-f522-483f-876f-f52149f3d1a7.png)

@Mateus13000
Edit /etc/passwd file on line apt

**Comment by Mateus13000** [comment]
![IMG_20220704_151033](https://user-images.githubusercontent.com/38146322/177202391-5610a2b0-4cf4-430d-ae38-1232b81375aa.jpg)

that's what happens when I try to install a package on manjaro

**Comment by Mateus13000** [comment]
> Can you access http://ports.ubuntu.com via browser? Is ping command work?

Yes and yes 😅

**Comment by Mateus13000** [comment]
> ![Screenshot_20220704-150343_Termux](https://user-images.githubusercontent.com/38641932/177110178-28eda951-f522-483f-876f-f52149f3d1a7.png)
> 
> @Mateus13000 Edit /etc/passwd file on line _apt

It worked! Thank you

**Comment by MrLucifer92** [comment]
How to port IP ؟ Ubuntu not updated
